name: build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: GCC 10 & GCOV
            CC: gcc-10
            CXX: g++-10
            use-odr: true
            use-gcov: true
          - name: Clang 10 & ODR
            CC: clang-10
            CXX: clang++-10

    env:
      CC: ${{matrix.CC}}
      CXX: ${{matrix.CXX}}
      USE_GCOV: ${{matrix.use-gcov == true}}
      ODR_TEST: ${{matrix.odr-test == true}}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure stuff
        run: |
          sudo apt install zstd
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DUSE_GCOV=$USE_GCOV -DODR_TEST=$ODR_TEST -DCMAKE_INSTALL_PREFIX=${{github.workspace}} ..

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . -j 6

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure

      - name: Upload coverage report
        working-directory: ${{github.workspace}}
        if: ${{matrix.use-gcov == true}}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.CoverallsToken }}
        run: |
          sudo apt install python3-setuptools python3-idna python3-requests python3-urllib3
          git clone https://github.com/PredatorCZ/cpp-coveralls.git
          pushd cpp-coveralls
          sudo python3 setup.py install
          popd
          export COVERALLS_SERVICE_NAME="gitlab-ci"
          coveralls -E ".*/build/.*.[ch]((pp)|(c)|(xx))?$" -e test -e 3rd_party --gcov-options '\-lp'

  build-widle:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure stuff
        run: |
          choco install ninja
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{github.workspace}} ..
        env:
          CC: clang
          CXX: clang++
      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . -j 6

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure
